
# docker
export DOCKER_NAMESPACE=jodafons

#expose to jupyter
export DOCKER_EXPOSE=8080

# virtualenv name
export VIRTUALENV_NAMESPACE='wgan-env'

# git control
export GIT_SOURCE_COMMIT=$(git rev-parse HEAD)

# lab storage environs
export PROJECT_DIR=/mnt/brics_data

# output 
export TARGET_DIR=$PWD/targets

# mlflow tracking
export TRACKING_DIR=$PROJECT_DIR/tracking

# data input
export DATA_DIR=$PROJECT_DIR/datasets

# repo
export REPO_DIR=$PWD

# maestro environs
export DATABASE_SERVER_URL=$POSTGRES_SERVER_URL

# logger level
export LOGURO_LEVEL="INFO"

# dorothy token
export DOROTHY_TOKEN="b16fe0fc92088c4840a98160f3848839e68b1148"


# export to singularity
export SINGULARITYENV_DOCKER_NAMESPACE=${DOCKER_NAMESPACE}
export SINGULARITYENV_DOCKER_EXPOSE=${DOCKER_EXPOSE}
export SINGULARITYENV_VIRTUALENV_NAMESPACE=${VIRTUALENV_NAMESPACE}
export SINGULARITYENV_PROJECT_DIR=${PROJECT_DIR}
export SINGULARITYENV_TARGET_DIR=${TARGET_DIR}
export SINGULARITYENV_DATA_DIR=${DATA_DIR}
export SINGULARITYENV_TACKING_DIR=${TRACKING_DIR}
export SINGULARITYENV_REPO_DIR=${REPO_DIR}
export SINGULARITYENV_DATABASE_SERVER_URL=$POSTGRES_SERVER_URL
export SINGULARITYENV_GIT_SOURCE_COMMIT=${GIT_SOURCE_COMMIT}
export SINGULARITYENV_LOGURO_LEVEL=${LOGURO_LEVEL}
export SINGULARITYENV_DOROTHY_TOKEN=$DOROTHY_TOKEN

